language: minimal

services:
  - docker

env:
  - DOCKER_IMAGE=rescuer/rescuer-la DOCKER_TAG=travis-$TRAVIS_BUILD_NUMBER

script:
  - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .

deploy:
  provider: script
  script:
    - docker login -u $SECRET_DOCKER_LOGIN -p $SECRET_DOCKER_PASSWORD
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:$TRAVIS_BRANCH
    - docker push $DOCKER_IMAGE:$TRAVIS_BRANCH
  on:
    all_branches: true
